// Ticker -> company/fund short name (Yahoo shortName). Static display lookup;
// regenerate if the symbol list changes.
export const SYMBOL_NAMES: Record<string, string> = {
  "SMH": "VanEck Semiconductor ETF",
  "NVDA": "NVIDIA Corporation",
  "AVGO": "Broadcom Inc.",
  "TSM": "Taiwan Semiconductor Manufactur",
  "AMD": "Advanced Micro Devices, Inc.",
  "MU": "Micron Technology, Inc.",
  "AMAT": "Applied Materials, Inc.",
  "LRCX": "Lam Research Corporation",
  "XLK": "State Street Technology Select",
  "MSFT": "Microsoft Corporation",
  "AAPL": "Apple Inc.",
  "CRM": "Salesforce, Inc.",
  "ORCL": "Oracle Corporation",
  "ADBE": "Adobe Inc.",
  "NOW": "ServiceNow, Inc.",
  "PANW": "Palo Alto Networks, Inc.",
  "XLC": "State Street Communication Serv",
  "META": "Meta Platforms, Inc.",
  "GOOGL": "Alphabet Inc.",
  "NFLX": "Netflix, Inc.",
  "DIS": "Walt Disney Company (The)",
  "TMUS": "T-Mobile US, Inc.",
  "VZ": "Verizon Communications Inc.",
  "CMCSA": "Comcast Corporation",
  "XLY": "State Street Consumer Discretio",
  "AMZN": "Amazon.com, Inc.",
  "TSLA": "Tesla, Inc.",
  "HD": "Home Depot, Inc. (The)",
  "MCD": "McDonald's Corporation",
  "NKE": "Nike, Inc.",
  "LOW": "Lowe's Companies, Inc.",
  "TJX": "TJX Companies, Inc. (The)",
  "XLF": "State Street Financial Select S",
  "BRK-B": "Berkshire Hathaway Inc. New",
  "JPM": "JP Morgan Chase & Co.",
  "V": "Visa Inc.",
  "MA": "Mastercard Incorporated",
  "MS": "Morgan Stanley",
  "GS": "Goldman Sachs Group, Inc. (The)",
  "BAC": "Bank of America Corporation",
  "XLV": "State Street Health Care Select",
  "LLY": "Eli Lilly and Company",
  "UNH": "UnitedHealth Group Incorporated",
  "JNJ": "Johnson & Johnson",
  "ABBV": "AbbVie Inc.",
  "MRK": "Merck & Company, Inc.",
  "AMGN": "Amgen Inc.",
  "ISRG": "Intuitive Surgical, Inc.",
  "XLI": "State Street Industrial Select",
  "GE": "GE Aerospace",
  "CAT": "Caterpillar, Inc.",
  "HON": "Honeywell International Inc.",
  "UNP": "Union Pacific Corporation",
  "LMT": "Lockheed Martin Corporation",
  "BA": "Boeing Company (The)",
  "DE": "Deere & Company",
  "XLE": "State Street Energy Select Sect",
  "XOM": "ExxonMobil Holdings Corporation",
  "CVX": "Chevron Corporation",
  "COP": "ConocoPhillips",
  "SLB": "SLB Limited",
  "EOG": "EOG Resources, Inc.",
  "MPC": "Marathon Petroleum Corporation",
  "PSX": "Phillips 66",
  "IWM": "iShares Russell 2000 Index Fund",
  "FTRE": "Fortrea Holdings Inc.",
  "VRT": "Vertiv Holdings, LLC",
  "SSTK": "Shutterstock, Inc.",
  "NSP": "Insperity, Inc.",
  "OUT": "OUTFRONT Media Inc.",
  "ENS": "EnerSys",
  "GTLB": "GitLab Inc.",
  "VEU": "Vanguard FTSE All World Ex US E",
  "SSNLF": "SAMSUNG ELECTRONICS CO",
  "SKHY": "SK hynix Inc.",
  "ASML": "ASML Holding N.V. - New York Re",
  "TCEHY": "Tencent Holding Ltd.",
  "NSRGY": "Nestle S.A.",
  "7203.T": "TOYOTA MOTOR CORP",
  "ARGT": "Global X MSCI Argentina ETF",
  "MELI": "MercadoLibre, Inc.",
  "YPF": "YPF Sociedad Anonima",
  "BMA": "Banco Macro S.A.",
  "GGAL": "Grupo Financiero Galicia S.A.",
  "PAM": "Pampa Energia S.A.",
  "CEPU": "Central Puerto S.A.",
  "LOMA": "Loma Negra Compania Industrial",
};
